// Generated by CoffeeScript 1.6.3
var NodeSassCompiler, sass;

sass = require('node-sass');

module.exports = NodeSassCompiler = (function() {
  NodeSassCompiler.prototype.brunchPlugin = true;

  NodeSassCompiler.prototype.type = 'stylesheet';

  NodeSassCompiler.prototype.extension = 'sass';

  NodeSassCompiler.prototype.pattern = /s[ac]ss$/;

  function NodeSassCompiler(config) {
    this.config = config;
  }

  NodeSassCompiler.prototype.compile = function(params, callback) {
    var _ref;
    return sass.render({
      outputStyle: (_ref = this.config) != null ? _ref.outputStyle : void 0,
      data: params.data,
      error: callback,
      success: function(css) {
        return callback(null, {
          data: css
        });
      }
    });
  };

  return NodeSassCompiler;

})();
