// Generated by CoffeeScript 1.6.3
var NodeSassCompiler, sass;

sass = require('node-sass');

module.exports = NodeSassCompiler = (function() {
  NodeSassCompiler.prototype.brunchPlugin = true;

  NodeSassCompiler.prototype.type = 'stylesheet';

  NodeSassCompiler.prototype.extension = 'sass';

  NodeSassCompiler.prototype.pattern = /s[ac]ss$/;

  function NodeSassCompiler(config) {
    var _ref;
    this.nodeSassConfig = (config != null ? (_ref = config.plugins) != null ? _ref.sass : void 0 : void 0) || {};
  }

  NodeSassCompiler.prototype.compile = function(params, callback) {
    return sass.render({
      outputStyle: this.nodeSassConfig.outputStyle,
      includePaths: this.nodeSassConfig.includePaths,
      data: params.data,
      error: callback,
      success: function(css) {
        return callback(null, {
          data: css
        });
      }
    });
  };

  return NodeSassCompiler;

})();
